### ISSUE TITLE
New image

### ISSUE THREAD

**Issue by pcav** [qgis-it/qgis-it.github.io#3]
Replace fuller\* with a generic name, and create a new image, similar to that one

**Comment by ghtmtt** [comment]
2 questions:
1. how many images should be created? .png and .svg?
2. after replacing, shouldn't we edit also the html or css?

**Comment by pcav** [comment]
1. check in the css which image is effectively used (I suspect the original is svg, compiled into png for rendering)
2. sure

**Comment by pcav** [comment]
Fixed
